# store a list of places I would like to visit, then manipulate it
places = ['ireland', 'norway', 'japan', 'wisconsin', 'canada']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse = True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse = True)
print(places)
